#############################################################################
# Makefile for building: vset
# Generated by qmake (2.01a) (Qt 4.7.0) on: Thu Apr 7 16:42:47 2011
# Project:  vset.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile vset.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -Ibuild -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/animatorwindow.cpp \
		src/CoverageModel.cpp \
		src/Experiment.cpp \
		src/ExperimentManager.cpp \
		src/main.cpp \
		src/mainwindowimpl.cpp \
		src/Model.cpp \
		src/PerturbationModel.cpp \
		src/pugixml.cpp \
		src/RenderWindow.cpp \
		src/ShotPoint.cpp \
		src/TimeModel.cpp \
		src/VelocityModel.cpp \
		src/Visualization.cpp \
		src/Workspace.cpp moc_animatorwindow.cpp \
		moc_mainwindowimpl.cpp
OBJECTS       = animatorwindow.o \
		CoverageModel.o \
		Experiment.o \
		ExperimentManager.o \
		main.o \
		mainwindowimpl.o \
		Model.o \
		PerturbationModel.o \
		pugixml.o \
		RenderWindow.o \
		ShotPoint.o \
		TimeModel.o \
		VelocityModel.o \
		Visualization.o \
		Workspace.o \
		moc_animatorwindow.o \
		moc_mainwindowimpl.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		vset.pro
QMAKE_TARGET  = vset
DESTDIR       = 
TARGET        = vset

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_animatorwindow.h ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: vset.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile vset.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile vset.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/vset1.0.0 || $(MKDIR) .tmp/vset1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/vset1.0.0/ && $(COPY_FILE) --parents src/animatorwindow.h src/Experiment.h src/ExperimentManager.h src/mainwindowimpl.h src/Model.h src/pugiconfig.hpp src/pugixml.hpp src/RenderWindow.h src/ShotPoint.h src/Visualization.h src/Workspace.h .tmp/vset1.0.0/ && $(COPY_FILE) --parents src/animatorwindow.cpp src/CoverageModel.cpp src/Experiment.cpp src/ExperimentManager.cpp src/main.cpp src/mainwindowimpl.cpp src/Model.cpp src/PerturbationModel.cpp src/pugixml.cpp src/RenderWindow.cpp src/ShotPoint.cpp src/TimeModel.cpp src/VelocityModel.cpp src/Visualization.cpp src/Workspace.cpp .tmp/vset1.0.0/ && $(COPY_FILE) --parents ui/animatorwindow.ui ui/mainwindow.ui .tmp/vset1.0.0/ && (cd `dirname .tmp/vset1.0.0` && $(TAR) vset1.0.0.tar vset1.0.0 && $(COMPRESS) vset1.0.0.tar) && $(MOVE) `dirname .tmp/vset1.0.0`/vset1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/vset1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_animatorwindow.cpp moc_mainwindowimpl.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_animatorwindow.cpp moc_mainwindowimpl.cpp
moc_animatorwindow.cpp: build/ui_animatorwindow.h \
		src/animatorwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/animatorwindow.h -o moc_animatorwindow.cpp

moc_mainwindowimpl.cpp: build/ui_mainwindow.h \
		src/Workspace.h \
		src/ExperimentManager.h \
		src/Experiment.h \
		src/pugixml.hpp \
		src/pugiconfig.hpp \
		src/ShotPoint.h \
		src/Model.h \
		src/Visualization.h \
		src/animatorwindow.h \
		build/ui_animatorwindow.h \
		src/mainwindowimpl.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindowimpl.h -o moc_mainwindowimpl.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_animatorwindow.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_animatorwindow.h ui_mainwindow.h
ui_animatorwindow.h: ui/animatorwindow.ui
	/usr/bin/uic-qt4 ui/animatorwindow.ui -o ui_animatorwindow.h

ui_mainwindow.h: ui/mainwindow.ui
	/usr/bin/uic-qt4 ui/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

animatorwindow.o: src/animatorwindow.cpp src/animatorwindow.h \
		build/ui_animatorwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animatorwindow.o src/animatorwindow.cpp

CoverageModel.o: src/CoverageModel.cpp src/Model.h \
		src/Experiment.h \
		src/pugixml.hpp \
		src/pugiconfig.hpp \
		src/ShotPoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CoverageModel.o src/CoverageModel.cpp

Experiment.o: src/Experiment.cpp src/Experiment.h \
		src/pugixml.hpp \
		src/pugiconfig.hpp \
		src/ShotPoint.h \
		src/Model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Experiment.o src/Experiment.cpp

ExperimentManager.o: src/ExperimentManager.cpp src/ExperimentManager.h \
		src/Experiment.h \
		src/pugixml.hpp \
		src/pugiconfig.hpp \
		src/ShotPoint.h \
		src/Model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExperimentManager.o src/ExperimentManager.cpp

main.o: src/main.cpp src/mainwindowimpl.h \
		build/ui_mainwindow.h \
		src/Workspace.h \
		src/ExperimentManager.h \
		src/Experiment.h \
		src/pugixml.hpp \
		src/pugiconfig.hpp \
		src/ShotPoint.h \
		src/Model.h \
		src/Visualization.h \
		src/animatorwindow.h \
		build/ui_animatorwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindowimpl.o: src/mainwindowimpl.cpp src/mainwindowimpl.h \
		build/ui_mainwindow.h \
		src/Workspace.h \
		src/ExperimentManager.h \
		src/Experiment.h \
		src/pugixml.hpp \
		src/pugiconfig.hpp \
		src/ShotPoint.h \
		src/Model.h \
		src/Visualization.h \
		src/animatorwindow.h \
		build/ui_animatorwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindowimpl.o src/mainwindowimpl.cpp

Model.o: src/Model.cpp src/Model.h \
		src/Experiment.h \
		src/pugixml.hpp \
		src/pugiconfig.hpp \
		src/ShotPoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Model.o src/Model.cpp

PerturbationModel.o: src/PerturbationModel.cpp src/Model.h \
		src/Experiment.h \
		src/pugixml.hpp \
		src/pugiconfig.hpp \
		src/ShotPoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PerturbationModel.o src/PerturbationModel.cpp

pugixml.o: src/pugixml.cpp src/pugixml.hpp \
		src/pugiconfig.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pugixml.o src/pugixml.cpp

RenderWindow.o: src/RenderWindow.cpp src/RenderWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RenderWindow.o src/RenderWindow.cpp

ShotPoint.o: src/ShotPoint.cpp src/ShotPoint.h \
		src/pugixml.hpp \
		src/pugiconfig.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ShotPoint.o src/ShotPoint.cpp

TimeModel.o: src/TimeModel.cpp src/Model.h \
		src/Experiment.h \
		src/pugixml.hpp \
		src/pugiconfig.hpp \
		src/ShotPoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TimeModel.o src/TimeModel.cpp

VelocityModel.o: src/VelocityModel.cpp src/Model.h \
		src/Experiment.h \
		src/pugixml.hpp \
		src/pugiconfig.hpp \
		src/ShotPoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VelocityModel.o src/VelocityModel.cpp

Visualization.o: src/Visualization.cpp src/Visualization.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Visualization.o src/Visualization.cpp

Workspace.o: src/Workspace.cpp src/Workspace.h \
		src/ExperimentManager.h \
		src/Experiment.h \
		src/pugixml.hpp \
		src/pugiconfig.hpp \
		src/ShotPoint.h \
		src/Model.h \
		src/Visualization.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Workspace.o src/Workspace.cpp

moc_animatorwindow.o: moc_animatorwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_animatorwindow.o moc_animatorwindow.cpp

moc_mainwindowimpl.o: moc_mainwindowimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindowimpl.o moc_mainwindowimpl.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

